apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec: 
  provider: azure
  parameters: 
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 7b76a661-3f2f-4e84-a2bc-0bc8f3a85496
    keyvaultName: ckw-aks-kv
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: app-insights-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: 38c7b18a-f92a-4353-a784-df16e895da23
  secretObjects:
    - data:
        - key: app-insights-connection-string
          objectName: app-insights-connection-string
      secretName: "aiconnectionstring"
      type: Opaque
